### ISSUE TITLE
exec: failed to write to cgroup.procs 

### ISSUE THREAD

**Issue by chavafg** [kata-containers/agent#476] opened 2019-03-12 22:26 UTC
# Description of problem

There have been some random failures with the hot plug CPUs and cri-o tests. Digging a little bit more into the failures, both are failing when running an exec command as follows:

cri-o failure:
```
05:34:59 # time="2019-03-11 11:34:57.715914943Z" level=debug msg="Received container exit code: -1, message: rpc error: code = Internal desc = Could not run process: container_linux.go:348: starting container process caused "process_linux.go:90: adding pid 169 to cgroups caused \"failed to write 169 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/Burstable/pod_123-456/crio-1e4648d38f30013bbdba2249f0eb8b7c043ef40d904fb5276c9ac71b4ba054f9/cgroup.procs: invalid argument\""
05:34:59 # " 
05:34:59 # time="2019-03-11T11:34:57Z" level=fatal msg="execing command in container synchronously failed: rpc error: code = Unknown desc = command error: rpc error: code = Internal desc = Could not run process: container_linux.go:348: starting container process caused "process_linux.go:90: adding pid 169 to cgroups caused \"failed to write 169 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/Burstable/pod_123-456/crio-1e4648d38f30013bbdba2249f0eb8b7c043ef40d904fb5276c9ac71b4ba054f9/cgroup.procs: invalid argument\""
05:34:59 # , stdout: , stderr: , exit code -1" 
```
docker failure:
```
Running command '/usr/bin/docker [docker exec TRpJ2dq55fITz0QLTuH49SPporH9nE cat /sys/fs/cgroup/cpuset/cpuset.cpus]'
command failed error 'exit status 126'
[docker exec TRpJ2dq55fITz0QLTuH49SPporH9nE cat /sys/fs/cgroup/cpuset/cpuset.cpus]
Timeout: 60 seconds
Exit Code: 126
Stdout: OCI runtime exec failed: rpc error: code = Internal desc = Could not run process: container_linux.go:348: starting container process caused "process_linux.go:90: adding pid 128 to cgroups caused \"failed to write 128 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/c81e621e3f3c96e7c1c05af8b814f9c507fbbe4fb017d50c8a3fa3edf2499b73/cgroup.procs: invalid argument\"": unknown
```
Some jobs affected by this issue:
http://jenkins.katacontainers.io/job/kata-containers-tests-fedora-PR/1236/consoleText
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-18-04-PR/126/consoleText
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-nemu/79/consoleText

**Comment by devimc** [comment] 2019-03-12 22:32
seems like this is a known issue that was already fixed https://github.com/opencontainers/runc/pull/1916

**Comment by jodh-intel** [comment] 2019-03-13 10:32
Does someone want to pick up [re-vendoring](https://github.com/kata-containers/community/blob/master/VENDORING.md) `runc` with this issue?

**Comment by chavafg** [comment] 2019-03-13 13:25
I can do it, but to what revision should I revendor?
`ccb5efd37fb7c86364786e9137e22948751de7ed` is `v1.0.0-rc6`, which is latest release and has the fix in it.
or do we want a newer revision?

**Comment by devimc** [comment] 2019-03-13 13:41
@chavafg use `f414f497b50a61750ea3af9fccf998a3db687cea` that is one before the cve

**Comment by sboeuf** [comment] 2019-03-18 19:53
@devimc could you investigate this issue as it seems to cause a bunch of instabilities in our CI. Also, from what I gathered from @chavafg feedback, https://github.com/kata-containers/agent/pull/477 might not be enough.
@chavafg @devimc please let us know what is the status on this issue as we want to fix it asap to get a more reliable CI, as we're delaying PRs right now because the CI never gets green on the first pass.

**Comment by sboeuf** [comment] 2019-03-18 22:30
@devimc @chavafg I've opened https://github.com/kata-containers/agent/pull/490 to fix the revendoring of libcontainer. PTAL

**Comment by devimc** [comment] 2019-03-19 13:50
thanks @sboeuf

**Comment by chavafg** [comment] 2019-04-02 13:56
Reopening this issue as #490 was reverted and we are still getting exec failures.

**Comment by sboeuf** [comment] 2019-04-02 14:23
@lifupan did you get a chance to investigate the failures related to the new libcontainer vendoring?

**Comment by lifupan** [comment] 2019-04-02 15:23
> @lifupan did you get a chance to investigate the failures related to the new libcontainer vendoring?

Hi @sboeuf , yes, actually I've dug on this issue and had found some clue about it.

**Comment by sboeuf** [comment] 2019-04-02 15:41
Oh nice, please share and submit any fix you got :)

**Comment by lifupan** [comment] 2019-04-03 13:47
Hi @sboeuf some info to update here: 
 I had found the root cause for shimv,2 failed on latest libcontainer, but the fix will bring 
another issue for shimv2, I'm debugging on how to solve it definitely, once I had figure out the patch,
I'll send it later.

**Comment by sboeuf** [comment] 2019-04-03 14:24
Great! Thanks @lifupan :+1:

**Comment by lifupan** [comment] 2019-04-11 12:21
Hi @sboeuf 
Since those PR https://github.com/kata-containers/runtime/pull/1494 and 
https://github.com/kata-containers/agent/pull/526
have been merged, I think it's time to reback your patches.

**Comment by sboeuf** [comment] 2019-04-11 16:35
@lifupan thanks for the heads up! Let's resubmit the vendoring update.

**Closed** 2019-04-11 19:07 UTC
Labels: bitesize
