### ISSUE TITLE
Fix Dockerfile used to regenerate gRPC golang code

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/agent#185] opened 2018-03-22 16:20 UTC
The `Dockerfile` used to regenerate the protocol buffer golang code currently:

- Fails to install golang

  Reason: URL incorrect:

  | | url |
  |--|--|
  | incorrect | `https://storage.googleapis.com/golang/go${GO_VERSION}.linux-$(arch).tar.gz` |
  | correct | `https://storage.googleapis.com/golang/go${GO_VERSION}.linux-${arch}.tar.gz` |

- fails to run `./hack/update-generated-agent-proto.sh`
  Reason: That script now uses https://github.com/gogo/protobuf/tree/master/protoc-gen-gogofast rather than https://github.com/golang/protobuf/protoc-gen-go.

It's also unclear to me why we're pinning the tool versions in `Dockerfile` to specific versions of the protobuf tooling?

**Comment by jshachm** [comment] 2018-05-08 06:13
@jodh-intel 
Different version of protobuf tools may generate different codes 
As you can see in #222 .When I use different version, I got different result.

**Comment by devimc** [comment] 2019-07-17 15:54
Closing issue, I couldn't reproduce this issue, please feel free to reopen it if you face this issue it again

**Closed by devimc** 2019-07-17 15:54 UTC
